server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui/api-docs.html

spring:
  application:
    name: USER-REGISTER-SERVICE
  data:
    mongodb:
      auto-index-creation: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost